services:
  - type: web
    name: audiorefine-backend
    env: python
    buildCommand: |
      pip install numpy==1.24.4 cython==0.29.36
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
